### PR TITLE
ability to read secrets from env files (e.g. Vault and Kubernetes)

### PR DESCRIPTION
**Pull request by kamsz**

### CODE REVIEW

**Comment by thomseddon** [comment]
You can specify a config file via the `-config` flag, would this not work?

**Comment by kamsz** [comment]
@thomseddon No, not really, as it would require special formatting. This way it's easier to use sidecars such as https://github.com/UKHomeOffice/vault-sidekick to feed the secrets into container.

**Comment by thomseddon** [comment]
I'm hoping to support the vault-sidekick or similar in v2, I will leave this open until that's merged.

**Comment by thomseddon** [comment]
This is now support in the version 2 branch, see #26 

Will close once documentation has been updated

**Comment by thomseddon** [comment]
The development branch has been released with the v2.0.0-rc1 tag on docker, it should be fully backwards compatible and supports applying multiple files, documentation here: https://github.com/thomseddon/traefik-forward-auth/tree/dev

**Pull request closed without merging**
