### PR TITLE
IP Whitelist

### PR DESCRIPTION
**Pull request by elliotmoso**
I have added the posibility to whitelist one or more IP/CIDR addresses.
I use it to allow free access from inside my enterprise network but requiring login when doing it from outside.
It's not a perfect implementation but works well. Also I have created a realip helper that allows to extract the real user ip when working behind a proxy like cloudflare or an enterprise proxy.

### CODE REVIEW

**Comment by thomseddon** [comment]
Hi,

Thanks for your work on this so far - at the moment this isn't an immediate merge for me as I don't believe white listing IPs is in keeping with the BeyondCorp model of authentication. My main issue is that you'd be unable to identify which user sent which request, so you could not offer fine grained access control on a per-service basis.

What's your use case for bypassing the authentication?

**Comment by elliotmoso** [comment]
We use this bypass in our preproduction environment.
In our case when we are in the office we don't need authentication to be faster, but we want to authenticate foregein access.
Also we have some private network access, in our case we allow access from 10.0.0.0/8 ip network because some internal api calls that must satisfy the same processing.

**Comment by thomseddon** [comment]
OK, another option would be to create another traefik frontend (on another port) with an IP whitelist in there to only allow access from your desired subnets?

I will leave this open for now so anyone who supports this can weigh in, but I'm not sure I love this concept at the moment.

**Comment by drubin** [comment]
Trusting these headers to determine source IP is a risky and not great security as any user could spoof these headers and you would assume they are coming from internal address. 

You can only trust headers like this if they are injected by the proxy and you have total trust that the proxy will strip out any spoofed headers. 

Any user that isn't running behind cloudflare would be exposed by just doing `curl -H CF-Connecting-IP: 10.0.0.1` or something similar... and traefik / this libary would never know the difference.

**Comment by thomseddon** [comment]
I'm closing this based on the earlier discussion, I'm glad you were able to implement a working solution for your use case but as noted, there's some risk associated with this method.

Thanks for taking the time to build the PR

**Pull request closed without merging**
