### PR TITLE
Fix rules argument

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This needed quite some changes cause I was confused from the current system and I did not want to introduce breaking changes.

**Comment by thomseddon** [comment]
Why do you think we should change this?

As it's a breaking change we'd also have to build the backwards compatibility, so I don't think it's worth it anyway.

**Comment by SuperSandro2000** [comment]
Cause the current system is broken and neither ``--rules.1.`` nor ``--rule.1.`` as an argument is accepted.

I did not introduce any breaking changes as it was already broken and did not work.

**Comment by thomseddon** [comment]
Apologies!

I misread the changes as changing functionality, I think I must have messed up the definition during the release, so thank you for spotting and fixing this!

Thank you

**Comment by SuperSandro2000** [comment]
No problem. Fixing this was quite confusing for me, too.

**Pull request merged**
