### PR TITLE
Fix redirect on AUTH_HOST mode

### PR DESCRIPTION
**Pull request by gites**
Signed-off-by: Denys Vitali <denys@denv.it>

### CODE REVIEW

**Comment by gites** [comment]
See https://github.com/thomseddon/traefik-forward-auth/pull/78#issuecomment-568544536 for purpose of this.

**Comment by thomseddon** [comment]
Thanks! I'm very willing to merge this, but I would like to introduce a test at the same time that shows what this is fixing, would you be able to do that?

**Comment by gites** [comment]
@thomseddon sure, I can prepare a test for this.

**Comment by thomseddon** [comment]
Just thinking about this a little more, if you're unable to quickly work out what this fixes, could you try reducing the patch down to the absolute fewest number of lines necessary to fix the bug?

As per previous discussion, a few people also seem to have had this issue, but it's not 100% clear what's causing this for a subset of people, or how exactly this fixes it.

Finally, please could you also post your config :)

**Comment by gites** [comment]
Sorry, I didn't have time to work on this true the Holidays. Quickly adding my config and example service with it.
On Google OAauth2 Credentials configuration page I have `https://auth0.example.com/_oauth` in Authorized redirect URIs and `https://auth0.example.com/` in Authorized JavaScript origins.

`traefik-forward-auth` configuration:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-auth0
  namespace: default
spec:
  selector:
    matchLabels:
      app: forward-auth0
  replicas: 1
  template:
    metadata:
      labels:
        app: forward-auth0
    spec:
      containers:
      - name: traefik-forward-auth
        image: gites/traefik-forward-auth:gites2
        args:
        - --log-level=trace
        - --auth-host=auth0.example.com
        - --cookie-domain=example.com
        - --cookie-name=example_auth0_oauth
        - --domain=anotherexample.com
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - containerPort: 4181
            protocol: TCP
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth0-secrets
                key: oauth2_proxy_client_id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth0-secrets
                key: oauth2_proxy_client_secret
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: auth0-secrets
                key: oauth2_proxy_cookie_secret
        livenessProbe:
          tcpSocket:
            port: 4181
          initialDelaySeconds: 20
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forward-auth0
  name: forward-auth0
  namespace: default
spec:
  ports:
  - port: 4181
    protocol: TCP
    targetPort: 4181
  selector:
    app: forward-auth0
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    certmanager.k8s.io/cluster-issuer: letsencrypt
  name: forward-auth0
spec:
  tls:
  - hosts:
    - auth0.example.com
    secretName: auth0-tls
  rules:
  - host: auth0.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: forward-auth0
          servicePort: 4181
```

Example Service and Ingress:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    certmanager.k8s.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: https://auth0.example.com
  name: echo2
spec:
  tls:
  - hosts:
    - echo2.example.com
    secretName: echo2-tls
  rules:
  - host: echo2.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echo2
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo2
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 5678
  selector:
    app: echo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo2
  namespace: default
spec:
  selector:
    matchLabels:
      app: echo2
  replicas: 1
  template:
    metadata:
      labels:
        app: echo2
    spec:
      containers:
      - name: echo2
        image: hashicorp/http-echo
        args:
        - "-text=¯\\_(ツ)_/¯ echo2"
        ports:
        - containerPort: 5678
```

**Comment by gites** [comment]
@thomseddon  Finally had some time to work on the code and tests 🎉 

This change fixes an issue where one was unable to authorize using `AUTH HOST` mode due to callback requests from Google being treated as unauthorized requests and redirect again to Google. The `AUTH HOST` callback request was handled by `AuthHandler` instead of `AuthCallbackHandler`.

I also fixed test after changes introduced in https://github.com/thomseddon/traefik-forward-auth/commit/c5dfb28df773128e83da5ab7170e84af43fae1ac

**Comment by thomseddon** [comment]
Hi @gites thanks for diving into this again, unfortunately the diff as proposed would mean that no AuthHandler would be attached if you're not using an AuthHost, so we'll need a different approach (this is actually also the case for the original commit: https://github.com/thomseddon/traefik-forward-auth/commit/da35933d58d45a4d6d4917682f4e42395eda2fc7)

I'm still puzzled by this, the proposed rule:
```
r.Rule = "Host(`" + config.AuthHost + "`) && Path(`"+ config.Path +"`)"
r.Action = "allow"
fr := r.formattedRule()
s.router.AddRoute(fr, 1, s.AuthCallbackHandler())
```

Can be simplified to just:
```
rule := "HostRegexp(`" + config.AuthHost + "`) && Path(`"+ config.Path +"`)"
s.router.Handle(rule, s.AuthCallbackHandler())
```

Is _more specific, so would still be matched by the existing rule:
```
s.router.Handle(config.Path, s.AuthCallbackHandler())
```

So I feel if this is fixing something then perhaps it's due to the priority? Again, it's puzzling as we're using this in production with an auth host and additional rules, without any redirect loop issues...

I've pushed up another branch with an example extra test, if you could find a way to make this fail (i.e. replicate the issue) then demonstrate how your branch could fix it - that would be ideal: https://github.com/thomseddon/traefik-forward-auth/tree/fix/auth-host-loop-test

**Comment by thomseddon** [comment]
Looking again, it can't be related to priority as `mux.SortRoutes` is never called, so the rules are left in the order they are added.

I'm still trying to replicate this, if you're able to record all the requests and responses when it's looping vs. when it's not, that could really help narrow it down so we can see what's occurring :)

**Comment by leoligz** [comment]
I am experiencing similar issue: The redirection from Google to `https://auth.example.com/_oauth?xxxx` is handled by the default AuthHandler instead of the AuthCallbackHandler, and therefore it's redirected back to `https://accounts.google.com/o/oauth2/auth`

**Comment by leoligz** [comment]
Debug showed that `req.URL.Path` (req.RequestURI is `/_oauth`) is empty so fails to match against the `/_oauth/` path. Will need to debug a bit more

**Comment by leoligz** [comment]
New to Traefik, so not sure how this AUTH_HOST should work: It seems to me Traefik only adds the X-Forwarded-Uri header when the ForwardAuth Middleware is in use, but should I add the Middleware in front of AUTH_HOST route? Wouldn't that be a loop?

**Comment by wanno-drijfhout** [comment]
> I've pushed up another branch with an example extra test, if you could find a way to make this fail (i.e. replicate the issue) then demonstrate how your branch could fix it - that would be ideal: https://github.com/thomseddon/traefik-forward-auth/tree/fix/auth-host-loop-test

Would you be able to push this development branch to https://hub.docker.com/r/thomseddon/traefik-forward-auth/tags? It'd make it easy for me to test locally (because I run a Docker swarm without a Docker registry yet, so compiling and publishing is a hassle).

I've looked at the code and it really seems like the [callback handler](https://github.com/thomseddon/traefik-forward-auth/blob/c3b4ba8244629255f1c03c54ebfe5f25650e37e4/internal/server.go#L40) is just not being registered or hit at all. Are those "routes" configured directly in Traefik? Should I see those routes in the Traefik dashboard, then? Because in the Traefik dashboard I really only see the routes I defined manually with tags in my Stack/Compose YAML file.

**Comment by bncbodrogi** [comment]
> Debug showed that `req.URL.Path` (req.RequestURI is `/_oauth`) is empty so fails to match against the `/_oauth/` path. Will need to debug a bit more.
> Any idea?

Also got stuck here. 
K8S + Traefik 2.2 + Azure AD oidc
If I add the forward-auth middleware to the forward-auth ingressroute that makes Traefik loop, protected_endpoint -> auth_endpoint -> protected endpoint ...

**Comment by leoligz** [comment]
I managed to get this AUTH_HOST working now on a Kubernetes + Traefik 2.2 + Letencrypt + Google + domain cookie setup. After reviewing the code of Traefik and this middleware, I put the middleware in front of both the app & the auth https IngressRoutes, while the middleware itself is pointing to the Service address inside K8s. I was pointing it to the https FQDN, which created a loop. 

```
apiVersion:` traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-auth
  namespace: oidc
spec:
  forwardAuth:
    address: http://oidc-traefik-forward-auth.oidc.svc:4181
    trustForwardHeader: true
    authResponseHeaders: ["X-Forwarded-User"]
```
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tlsingressroute
  namespace: oidc
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`auth.example.org`)
    kind: Rule
    middlewares:
    - name: oidc-test-auth@kubernetescrd
    services:
    - name: oidc-traefik-forward-auth
      port: 4181
  - match: Host(`whoami.example.org`)
    kind: Rule
    middlewares:
    - name: oidc-test-auth@kubernetescrd
    services:
    - name: whoami
      port: 80
  tls:
    certResolver: letsencrypt
    domains:
    - main: example.org
      sans:
      - auth.example.org
      - whoami.example.org
```

**Comment by bncbodrogi** [comment]
@leoligz Thanks mate, I really appreciate your reply. I tried the same but it didn't work. If I define a single middleware for the forward-auth and put it on the forward-auth ingress route as well as the other protected routes Traefik brakes.

My solution was the following.

- Define a separate routing rule for the `_oauth` path and the host and make sure that the one pointing to root -> `Host("auth.mycompany.comq")` has lower precedence. 

- Also, I had to comment out a section in the [RootHandler](https://github.com/thomseddon/traefik-forward-auth/blob/c3b4ba8244629255f1c03c54ebfe5f25650e37e4/internal/server.go#L49-L59) function like this.
*Mind that I only suspect that this is due to the changes in traefik 2.2, not a 100% sure* 🙈.
```
func (s *Server) RootHandler(w http.ResponseWriter, r *http.Request) {

	//Not needed in Traefik 2.0

	// Modify request
	// r.Method = r.Header.Get("X-Forwarded-Method")
	// r.Host = r.Header.Get("X-Forwarded-Host")
	// r.URL, _ = url.Parse(r.Header.Get("X-Forwarded-Uri"))

	// Pass to mux
	s.router.ServeHTTP(w, r)
}
```
Config below.

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: fwdauth
  name: fwdauth
  namespace: default
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Path(`/_oauth`)
    priority: 2
    services:
    - name: fwdauth
      port: 80
    middlewares:
    - name: fake-https
  - kind: Rule
    match: Host(`auth.mycompany.com`)
    priority: 1
    services:
    - name: fwdauth
      port: 80
    middlewares:
    - name: fake-https
---
```
**Note**: We're on AWS with a managed EKS, using an NLB. The TLS termination happens on the load balancer, hence the `web` entry point and the `fake-https` middleware which will rewrite the `X-Forwarded-Proto` header so the redirect-url is still correct on the outgoing request to azure.

**Comment by thomseddon** [comment]
As per my [comment](https://github.com/thomseddon/traefik-forward-auth/issues/79#issuecomment-652018384) in #79 I believe that the problem that this "fixes" is the bug as described in #129 

The problem is caused when the authentication middleware is not applied the the tfa ingress, @bncbodrogi's example works as the middleware is correctly applied.

This is "fixed" by https://github.com/thomseddon/traefik-forward-auth/commit/da35933d58d45a4d6d4917682f4e42395eda2fc7 as this falls back to parsing the actual given URI when X-Forwarded-Uri is empty

The examples have now been expanded significantly to show the advised setup to k8s, swarm in both traefik v1.7 and 2+.

I'm going to implement a fix to support the situation where the authentication middleware hasn't been applied and I'll track the progress of that in #129

**Pull request closed without merging**
