### PR TITLE
Multiple Provider Support + OIDC Support

### PR DESCRIPTION
**Pull request by thomseddon**
This is a major refactor that allows us to support multiple providers.

Also included is a complete OIDC provider + base class for easily implementing further providers supported by https://golang.org/x/oauth2

Work still needed:

- [x] Tidy up pre-existing provider tests
- [x] Live OIDC testing (ensure unit tests are valid)

### CODE REVIEW

**Comment by thomseddon** [comment]
This is ready to merge now, I'll do a bit more end-to-end testing next week and then get this released!

**Comment by thomseddon** [comment]
Rebased and updated dependencies in preparation for release

**Comment by danielmccosker** [comment]
Hiya, 

I realise this branch is pre-release but I've noticed some unexpected behaviour.

Even though I have set env vars OIDC_ISSUER_URL, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET the container fails to start with the message:

level=fatal msg="providers.oidc.issuer-url, providers.oidc.client-id, providers.oidc.client-secret must be set"

Which I believe is due to this snippet in providers.go where the OIDC provider namespaces are O_DI_C:

`
type Providers struct {
	Google Google `group:"Google Provider" namespace:"google" env-namespace:"GOOGLE"`
	OIDC   OIDC   `group:"ODIC Provider" namespace:"odic" env-namespace:"ODIC"`
}
`

**Comment by thomseddon** [comment]
Hey - Thanks! I was testing this yesterday and found the issue with the env var, so thanks for saving me the time by finding the root cause :)

**Comment by thomseddon** [comment]
Updates made, published to docker hub on tag [v2.1.0-rc1](https://hub.docker.com/layers/thomseddon/traefik-forward-auth/v2.1.0-rc1/images/sha256-4c08f53a39d56f61b25656dffdaf93bb14ef9dce2baac62aecc049f1ea255227) - I've just deployed this into our production environment without any issues!

Will get this released this week!

**Comment by FuNK3Y** [comment]
I tested rc1, but even with env vars: OIDC_ISSUER_URL, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, and I get:

`time="2020-01-30T07:20:01Z" level=fatal msg="providers.google.client-id, providers.google.client-secret must be set"`

Do I need to specify the provider somewhere? I didn't had the time to go through the PR

**Comment by thomseddon** [comment]
Thanks for testing!

Yes, my last job is documentation, you can set the provider gloablly with `--default-provider=oidc" and "DEFAULT_PROVIDER=oidc" or you can specify a provider just in one rule with: `rule.1.provider=oidc"

:)

**Comment by pierresteiner** [comment]
> Thanks for testing!
> 
> Yes, my last job is documentation, you can set the provider gloablly with `--default-provider=oidc` and `DEFAULT_PROVIDER=oidc` or you can specify a provider just in one rule with: `rule.1.provider=oidc`
> 
> :)

Thanks, I tried it but with a typo. Now I the provider selection working, but it does still complain:
`time="2020-01-30T12:30:21Z" level=fatal msg="providers.oidc.issuer-url, providers.oidc.client-id, providers.oidc.client-secret must be set"`

Here is what I configured (docker compose):
```
- DEFAULT_PROVIDER=oidc
- ISSUER_URL=https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
- CLIENT_ID=
- CLIENT_SECRET=
- SECRET=
- COOKIE_DOMAIN=
- AUTH_HOST=
- WHITELIST=
```
I also tried with:
```
- DEFAULT_PROVIDER=oidc
- OIDC_ISSUER_URL=https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
- OIDC_CLIENT_ID=
- OIDC_CLIENT_SECRET=
- SECRET=
- COOKIE_DOMAIN=
- AUTH_HOST=
- WHITELIST=
```
Any idea about what I am doing wrong?

**Comment by thomseddon** [comment]
So to configure the provider you can use:

```
OIDC Provider:
      --providers.oidc.issuer-url=      Issuer URL [$PROVIDERS_OIDC_ISSUER_URL]
      --providers.oidc.client-id=       Client ID [$PROVIDERS_OIDC_CLIENT_ID]
      --providers.oidc.client-secret=   Client Secret [$PROVIDERS_OIDC_CLIENT_SECRET]
```

**Comment by pierresteiner** [comment]
Thanks, I tested it with MS Azure and it is working flawlessly

**Comment by pierresteiner** [comment]
Tested with Okta; it is also working fine here.

**Comment by thomseddon** [comment]
This is ready to go, I just need to finish the docs (almost done :)

**Comment by Rathna-K** [comment]
Hi @thomseddon so if I pull the :latest tag from docker for ARM/ Raspberry Pi will these changes be included? so for ARM also it is 2.1 Prod?  thanks!

**Comment by Rathna-K** [comment]
> Thanks, I tested it with MS Azure and it is working flawlessly

can you provide some guidance how you got it to work please? maybe share the docker-compose  ?

**Comment by FuNK3Y** [comment]
> > Thanks, I tested it with MS Azure and it is working flawlessly
> 
> can you provide some guidance how you got it to work please? maybe share the docker-compose ?

Sure, here it is:
```yaml
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_FOLDER}/traefik:/data
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:172.17.0.1 # Temporary fix until docker fix this mess
    restart: always
    command:
      - --api
      - --providers.file.directory=/data
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultrule=Host(`{{ normalize .Name | replace "-${COMPOSE_PROJECT_NAME}" ".${DOMAIN}"}}`)
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.default.acme.httpchallenge=true
      - --certificatesresolvers.default.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.default.acme.storage=/data/acme.json
      - --entrypoints.websecure.http.tls.certresolver=default
      - --entrypoints.websecure.http.middlewares=sts
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      # Global settings
      - traefik.http.middlewares.sts.headers.stspreload=true
      - traefik.http.middlewares.sts.headers.stsseconds=31536000

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=${OIDC_ISSUER}
      - PROVIDERS_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - PROVIDERS_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - SECRET=${TFA_SECRET}
      - COOKIE_DOMAIN=${DOMAIN}
      - AUTH_HOST=traefik-forward-auth.${DOMAIN}
      - WHITELIST=${TFA_WHITELIST}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-forward-auth.middlewares=auth
      - traefik.http.routers.traefik-forward-auth.entrypoints=websecure
      - traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181
      - traefik.http.middlewares.auth.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.auth.forwardauth.authresponseheaders=X-Forwarded-User
    restart: always

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    command: --no-auth
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.middlewares=auth
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
```
`$OIDC_ISSUER`=`OIDC_ISSUER=https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0` - with `9188040d-6c67-4c5b-b112-36a304b66dad` being the ID of the tenant (in my case  this is the common one (Live, XBOX & co).

You can use https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc for reference.

**Comment by Rathna-K** [comment]
Thank you for sharing it. I am trying to use my office 365 tenant ID but i keep seeing this redirect error in the traefik-forward-Auth log

level=fatal msg="oidc: issuer did not match the issuer returned by provider, expected \"https://login.microsoftonline.com/tenant Id \" got \"https://sts.windows.net/tenant id

Any idea why?

**Pull request merged**
