### PR TITLE
Allow override of domains and whitelist in rules

### LINKED ISSUE #57: Whitelist per TFA domain?
Precondition: I have one TFA instance deployed, with for example google auth configured.
i want to secure both domain1 & domain2; but domain1 i would only want to allow some@user.com and for domain2 i want to allow both users. Is this currently possible to use docker compose and inject separate whitelists per container?

### PR DESCRIPTION
**Pull request by lozlow**
Builds on the work of mathcantin in #63

- Implements PR feedback
- Resolves merge conflicts

Closes #57 
Closes #63

### CODE REVIEW

**Comment by lozlow** [comment]
Ah woops, more conflicts 🙂, I'll get this updated

**Comment by lozlow** [comment]
This is ready for review, thanks!

**Comment by tdorsey** [comment]
@lozlow Looks like we worked this one simultaneously. Would you mind to have a look at #133 and see what you think? My implementation is slightly different. It combines address/domain whitelists into one field, and respects the MatchWhitelistOrDomain property instead of having the rule override the global config entirely

**Comment by ilteoood** [comment]
+1 for this.
I really need it!

**Comment by thomseddon** [comment]
Merged in #169 - thanks again!

**Pull request closed without merging**
