### PR TITLE
Add automatic image support for various archs

### PR DESCRIPTION
**Pull request by IslamAlam**
The modification allows for automatic image support for various archs.

Added manifest file for the docker image for multi-arch support. 

I have added the build to this repo which support multi-arch:
https://hub.docker.com/repository/docker/imansour/traefik-forward-auth/

Supported arch:
linux/amd64, linux/386, linux/arm64, linux/ppc64le, linux/s390x, linux/arm/v7, linux/arm/v6

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
You are mixing tabs and spaces.

**Comment by thomseddon** [comment]
Sorry If I'm missing something here - but doesn't go default to building on whatever arch your currently on anyway?

**Comment by SuperSandro2000** [comment]
@thomseddon you are right. Totally missed that.

**Comment by IslamAlam** [comment]
@SuperSandro2000 @thomseddon I think this PR would not be needed then as PR #116 already introduced. I include the PR as I was using buildx for building the images for supporting multi arch:
https://hub.docker.com/repository/docker/imansour/traefik-forward-auth/tags?page=1

**Pull request closed without merging**
